// Data storage
let customData = [];
const defaultData = {
  male: [
  {
    "Name": [
      "Adi",
      "Aditya",
      "Adri",
      "Adrie",
      "Agung",
      "Agus",
      "Ahmad",
      "Aji",
      "Alan",
      "Aldi",
      "Alex",
      "Andre",
      "Andri",
      "Angkasa",
      "Anwar",
      "Aprilio",
      "Ardi",
      "Ardy",
      "Arief",
      "Arif",
      "Awig",
      "Bagus",
      "Bambang",
      "Baswedan",
      "Bayu",
      "Bima",
      "Bimo",
      "Budi",
      "Candra",
      "Darmawan",
      "Desvan",
      "Dewandaru",
      "Dhani",
      "Didik",
      "Didit",
      "Dilla",
      "Dimas",
      "Dwi",
      "Eko",
      "Faisal",
      "Fajar",
      "Gibran",
      "Guruh",
      "Hanshel",
      "Heri",
      "Hermawan",
      "Heru",
      "Hery",
      "Ibnu",
      "Iskandar",
      "Iswahyudi",
      "Iwan",
      "Joko",
      "Kamil",
      "Kevin",
      "Krisna",
      "Lana",
      "Maulana",
      "Miswan",
      "Nugroho",
      "Nusantara",
      "Oktavianto",
      "Pamungkas",
      "Pangestu",
      "Prabowo",
      "Pratama",
      "Purnomo",
      "Puryanto",
      "Raka",
      "Reza",
      "Ricky",
      "Ridwan",
      "Ririn",
      "Risang",
      "Riski",
      "Riyanto",
      "Rizki",
      "Rizky",
      "Saloka",
      "SandiagaUno",
      "Santoso",
      "Saputra",
      "Saputro",
      "Setiawan",
      "Setiyawan",
      "Subianto",
      "Surya",
      "Syarif",
      "Taulany",
      "Tio",
      "Tri",
      "Trisnandar",
      "Tyo",
      "Uno",
      "Widodo",
      "Yoga",
      "Yudha",
      "Yusuf",
      "Zolla"
    ],
    "Origin": "Indonesia",
    "Gender": "Male"
  },
  {
    "Name": [
      "Naoto",
      "Yamada",
      "Taguchi",
      "Morita",
      "Madoka",
      "Okamoto",
      "Iwao",
      "Haruto",
      "Sumiya",
      "Sudo",
      "Sakuma",
      "Hanakawa",
      "Youta Murakami",
      "Ikeuchi",
      "Subaru",
      "Kaito",
      "Isao Kusaga",
      "Sanbe Tadanori",
      "Shuuichi Kagaya"
    ],
    "Origin": "Gleipnir",
    "Gender": "Male"
  },
  {
    "Name": [
      "Uryuu Ishida",
      "Zaraki Kenpachi",
      "Kisuke Urahara",
      "Aizen Sousuke",
      "Toushirou Hitsugaya",
      "Byakuya Kuchiki",
      "Grimmjow Jaegerjaquez",
      "Shunsui Jirou Sakuranosuke Kyouraku",
      "Renji Abarai",
      "Shinji Hirako",
      "Kon",
      "Sado Yatsutora",
      "Hisagi Shuuhei",
      "Ukitake Juushirou",
      "Madarame Ikkaku",
      "Zangetsu",
      "Yamamoto Genryuusai Shigekuni",
      "Yhwach",
      "Kurosaki Isshin",
      "Gilga Nnoitra",
      "Ayasegawa Yumichika",
      "Izuru Kira",
      "Sajin Komamura",
      "Kensei Muguruma",
      "Kaname Tousen",
      "Tsukishima Shuukurou",
      "Nimaiya Ouetsu",
      "Ginjou Kuugo",
      "Hyousube Ichibei",
      "Ishida Ryuuken",
      "Black Bazzard",
      "Shiba Ganju",
      "Opie Quilge",
      "Akon",
      "Yuki Ryuunosuke",
      "Kutsuzawa Giriko"
    ],
    "Origin": "Bleach",
    "Gender": "Male"
  },
  {
    "Name": [
      "Aki Hayakawa",
      "Kishibe",
      "Yoshida",
      "Beam",
      "Galgali",
      "Hirokazu Arai",
      "Yuutarou Kurose",
      "Madoka",
      "Taiyou Hayakawa",
      "Fushi",
      "Takashi Inoue",
      "Furuno",
      "Shuzou Mishima"
    ],
    "Origin": "Chainsaw Man",
    "Gender": "Male"
  },
  {
    "Name": [
      "Kamado Tanjirou",
      "Kagaya Ubuyashiki",
      "Giyu Tomioka",
      "Obanai Iguro",
      "Sanemi Shinazugawa",
      "Gyomei Himajima",
      "Muichiro Tokito",
      "Kyojurou Rengoku",
      "Sakonji Urodaki",
      "Jigoro Kuwajima",
      "Shinjuro Rengoku",
      "Tengen Uzui",
      "Zenitsu Agatsuma",
      "Inosuke Hashibira",
      "Genya Shinazugawa",
      "Murata",
      "Takeuchi",
      "Nagakura",
      "Noguchi",
      "Yoshioka",
      "Shimamoto",
      "Yoriichi Tsugikuni",
      "Goto",
      "Hotaru Haganezuka",
      "Kozo Kanamori",
      "Tecchin Tecchikawahara",
      "Kotetsu",
      "Tetsudoji",
      "Tetsutani",
      "Tetsuido",
      "Muzan Kibutsuji",
      "Yushiro",
      "Yahaba",
      "Tanjuro Kamado",
      "Takeo Kamado",
      "Shigeru Kamado",
      "Rokuta Kamado",
      "Sumiyoshi Kamado",
      "Saburo",
      "Sabito",
      "Toyo",
      "Yatsu",
      "Shoichi",
      "Kiyoshi",
      "Tatsu",
      "Senjuro Rengoku",
      "Kyogo Shinazugawa",
      "Michikatsu Tsugikuni",
      "Kaigaku",
      "Akaza",
      "Doma",
      "Kokushibou",
      "Hantengu",
      "Gyokko",
      "Gyutaro",
      "Enmu",
      "Kyogai",
      "Rokuro",
      "Wakuraba",
      "Hairo",
      "Keizo",
      "Talaharu",
      "Yoshiteru",
      "Kanata",
      "Aoba",
      "Giichi",
      "Sanehiro",
      "Tenma",
      "Tojuro"
    ],
    "Origin": "Kimetsu",
    "Gender": "Male"
  },
  {
    "Name": [
      "Akagami Shanks",
      "Aramaki",
      "Arlong",
      "Ashura Doji",
      "Bartolomeo",
      "Basil Hawkins",
      "Bellamy",
      "Benn Beckman",
      "Bepo",
      "Borsalino",
      "Cabaji",
      "Caesar Clown",
      "Capone Bege",
      "Capote",
      "Caribou",
      "Charlos",
      "Charlotte Katakuri",
      "Chinjao",
      "Chiya",
      "Clou D. Clover",
      "Denjiro",
      "Donquixote Doflamingo",
      "Donquixote Homing",
      "Donquixote Mjosgard",
      "Donquixote Rosinante",
      "Dracule Mihawk",
      "Edward Newgate",
      "Edward Weevil",
      "Eustass Kid",
      "Figarland Garling",
      "Fisher Tiger",
      "Foxy",
      "Franky",
      "Gecko Moria",
      "Gol D. Roger",
      "Hack",
      "Hajrudin",
      "Helmeppo",
      "Hody Jones",
      "Inuarashi",
      "Inukai",
      "Issho",
      "Izou",
      "Jaguar D. Saul",
      "Jinbe",
      "Joy Boy",
      "Kin'emon",
      "King",
      "Koby",
      "Kouzuki Momonosuke",
      "Kouzuki Oden",
      "Kouzuki Sukiyaki",
      "Krieg",
      "Kurozumi Kanjuro",
      "Kurozumi Orochi",
      "Kurozumi Semimaru",
      "Kuzan",
      "Kyros",
      "Laboon",
      "Magellan",
      "Marshall D. Teach",
      "Monkey D. Dragon",
      "Monkey D. Garp",
      "Monkey D. Luffy",
      "Mont Blanc Cricket",
      "Mont Blanc Noland",
      "Nekomamushi",
      "Neptune",
      "Page One",
      "Pedro",
      "Pica",
      "Portgas D. Ace",
      "Rob Lucci",
      "Rocks D. Xebec",
      "Roronoa Arashi",
      "Roronoa Pinzoro",
      "Roronoa Zoro",
      "Scratchmen Apoo",
      "Sengoku",
      "Senor Pink",
      "Shiki",
      "Shimotsuki Koushirou",
      "Shimotsuki Kouzaburou",
      "Shimotsuki Ryuma",
      "Shimotsuki Ushimaru",
      "Shimotsuki Yasuie",
      "Silvers Rayleigh",
      "Tony Tony Chopper",
      "Trafalgar D. Water Law",
      "Usopp",
      "Vegapunk",
      "Vergo",
      "Vinmsoke Sanji",
      "Vinsmoke Ichiji",
      "Vinsmoke Judge",
      "Vinsmoke Niji",
      "Vinsmoke Yonji",
      "Vista",
      "X Drake"
    ],
    "Origin": "One Piece",
    "Gender": "Male"
  },
  {
    "Name": [
      "Bill Watkins",
      "Billy Squire",
      "Bond Forger",
      "Byron Blackbell",
      "Carrol Campbell",
      "Cavi Campbell",
      "Damian Desmond",
      "Demetrius Desmond",
      "Dominic",
      "Donovan Desmond",
      "Edgar",
      "Emile Elman",
      "Ewen Egeburg",
      "Franky Franklin",
      "Gascoigne",
      "George Glooman",
      "Henry Henderson",
      "Jeeves",
      "Keith Kepler",
      "Loid Forger",
      "Matthew McMahon",
      "Murdoch Swan",
      "Sigmund Authen",
      "Winston Wheeler",
      "Yuri Briar"
    ],
    "Origin": "SPYxFAMILY",
    "Gender": "Male"
  },
  {
    "Name": [
      "Beom soo",
      "Byeong cheol",
      "Byeong heon",
      "Byung ho",
      "Byung hoon",
      "Byung joon",
      "Byung woo",
      "Byung wook",
      "Chan woo",
      "Chan young",
      "Chang ho",
      "Chang hoon",
      "Chang min",
      "Chang nam",
      "Chang woo",
      "Cheol min",
      "Chi won",
      "Chul",
      "Chul soo",
      "Chul soon",
      "Chul woo",
      "Dae hyun",
      "Dae sung",
      "Dae won",
      "Deok su",
      "Do hun",
      "Do hyun",
      "Do won",
      "Dong chan",
      "Dong chul",
      "Dong geun",
      "Dong gun",
      "Dong ha",
      "Dong hoon",
      "Dong hyuk",
      "Dong hyun",
      "Dong il",
      "Dong jun",
      "Dong seok",
      "Dong soo",
      "Dong won",
      "Dong woo",
      "Dong wook",
      "Geun",
      "Gi ung",
      "Gun",
      "Gyeong gu",
      "Ha joon",
      "Hae il",
      "Hae seong",
      "Han jae",
      "Ho",
      "Ho cheol",
      "Ho jin",
      "Ho jun",
      "Ho sung",
      "Hong gi",
      "Hoon",
      "Hui cheol",
      "Hyeong won",
      "Hyuk",
      "Hyuk jae",
      "Hyun jun",
      "Hyun seok",
      "Hyun seung",
      "Hyun sik",
      "Hyun tae",
      "Hyun woo",
      "Hyun wook",
      "Hyung joon",
      "Hyung min",
      "Hyungsik",
      "Il",
      "Il sung",
      "In sik",
      "Jae beom",
      "Jae Bong",
      "Jae geun",
      "Jae ho",
      "Jae hyuk",
      "Jae hyun",
      "Jae jin",
      "Jae joon",
      "Jae joong",
      "Jae kuk",
      "Jae seop",
      "Jae suk",
      "Jae sung",
      "Jae woo",
      "Jae wook",
      "Jae woong",
      "Jae yong",
      "Jeong ho",
      "Jeong sik",
      "Ji hoon",
      "Ji hwan",
      "Ji seok",
      "Ji tae",
      "Ji woon",
      "Ji woong",
      "Jin gyu",
      "Jin hwan",
      "Jin hyuk",
      "Jin sun",
      "Jin woo",
      "Jin wook",
      "Jin woon",
      "Jinwoo",
      "Jinwook",
      "Jinwoon",
      "Jong ho",
      "Jong hun",
      "Jong hyuk",
      "Jong hyun",
      "Jong il",
      "Jong seok",
      "Jong soo",
      "Jong yul",
      "Jongho",
      "Jonghun",
      "Jonghyuk",
      "Jonghyun",
      "Jongil",
      "Jongseok",
      "Jongsoo",
      "Jongyul",
      "Joo hwan",
      "Jooheon",
      "Joohwan",
      "Joon ho",
      "Joon ki",
      "Joon Sup",
      "Joon tae",
      "Joong ki",
      "Joongki",
      "Joonho",
      "Joonki",
      "JoonSup",
      "Joontae",
      "Ju ho",
      "Juho",
      "Jun ha",
      "Jun hyeok",
      "Jun sang",
      "Jun seo",
      "Jun seok",
      "Jun su",
      "Jung hoon",
      "Jung hwan",
      "Jung il",
      "Jung jin",
      "Jung mo",
      "Jung myung",
      "Jung nam",
      "Junghoon",
      "Junghwan",
      "Jungil",
      "Jungjin",
      "Jungmo",
      "Jungmyung",
      "Jungnam",
      "Junha",
      "Junhyeok",
      "Junsang",
      "Junseo",
      "Junseok",
      "Junsu",
      "Kang min",
      "Kangmin",
      "Ki ha",
      "Ki jung",
      "Ki moon",
      "Ki nam",
      "Ki tae",
      "Ki woo",
      "Kiha",
      "Kijung",
      "Kimoon",
      "Kinam",
      "Kitae",
      "Kiwoo",
      "Kun woo",
      "Kunwoo",
      "Kwang ho",
      "Kwang hoon",
      "Kwang hwan",
      "Kwang hyok",
      "Kwang hyun",
      "Kwang jo",
      "Kwang min",
      "Kwang seok",
      "Kwang seon",
      "Kwang sik",
      "Kwang su",
      "Kwangho",
      "Kwanghoon",
      "Kwanghwan",
      "Kwanghyok",
      "Kwanghyun",
      "Kwangjo",
      "Kwangmin",
      "Kwangseok",
      "Kwangseon",
      "Kwangsik",
      "Kwangsu",
      "Kyu chul",
      "Kyuchul",
      "Kyuhyun",
      "Kyung chul",
      "Kyung ho",
      "Kyung hwan",
      "Kyung jae",
      "Kyung joon",
      "Kyung mo",
      "Kyung seok",
      "Kyung soo",
      "Kyung tae",
      "Kyung taek",
      "Kyung wan",
      "Kyungchul",
      "Kyungho",
      "Kyunghwan",
      "Kyungjae",
      "Kyungjoon",
      "Kyungmo",
      "Kyungseok",
      "Kyungsoo",
      "Kyungtae",
      "Kyungtaek",
      "Kyungwan",
      "Man seok",
      "Man sik",
      "Man su",
      "Manseok",
      "Mansik",
      "Mansu",
      "Min chul",
      "Min ho",
      "Min hyuk",
      "Min jun",
      "Min ki",
      "Min kyu",
      "Min seok",
      "Min woo",
      "Minchul",
      "Minho",
      "Minhyuk",
      "Minjun",
      "Minki",
      "Minkyu",
      "Minseok",
      "Minwoo",
      "Moon sik",
      "Moon soo",
      "Moonsik",
      "Moonsoo",
      "Mu yeol",
      "Muyeol",
      "Myung bak",
      "Myung hoon",
      "Myung hwan",
      "Myung jun",
      "Myung soo",
      "Myung yong",
      "Myungbak",
      "Myunghoon",
      "Myunghwan",
      "Myungjun",
      "Myungsoo",
      "Myungyong",
      "Nam gi",
      "Nam il",
      "Nam jun",
      "Namgi",
      "Namil",
      "Namjun",
      "Oh seong",
      "Ohseong",
      "Sang cheol",
      "Sang hoon",
      "Sang hyun",
      "Sang jun",
      "Sang won",
      "Sang woo",
      "Sangcheol",
      "Sanghoon",
      "Sanghyun",
      "Sangjun",
      "Sangwon",
      "Sangwoo"
    ],
    "Origin": "Korean",
    "Gender": "Male"
  }

],
  female: [
  {
    "Name": [
      "Ayase",
      "Ai",
      "Aoi",
      "Aika",
      "Aiko",
      "Aimi",
      "Aina",
      "Aino",
      "Aira",
      "Airi",
      "Akane",
      "Akari",
      "Akemi",
      "Akeno",
      "Aki",
      "Akie",
      "Akiko",
      "Akina",
      "Akino",
      "Akiyo",
      "Ako",
      "Akoya",
      "Amane",
      "Ami",
      "Amina",
      "Anju",
      "Anna",
      "Anzu",
      "Ariko",
      "Arina",
      "Arisa",
      "Asaka",
      "Asako",
      "Asami",
      "Asuka",
      "Asumi",
      "Asuna",
      "Atsuko",
      "Atsumi",
      "Aya",
      "Ayaka",
      "Ayako",
      "Ayame",
      "Ayami",
      "Ayana",
      "Ayane",
      "Ayano",
      "Ayasa",
      "Ayu",
      "Ayuka",
      "Ayuko",
      "Ayumi",
      "Ayumu",
      "Azumi",
      "Chidori",
      "Chie",
      "Chieko",
      "Chiemi",
      "Chigusa",
      "Chiharu",
      "Chihaya",
      "Chiho",
      "Chika",
      "Chikage",
      "Chikako",
      "Chinami",
      "Chinatsu",
      "Chisato",
      "Chitose",
      "Chiya",
      "Chiyako",
      "Chiyo",
      "Chiyoko",
      "Chizuko",
      "Chizuru",
      "Eiko",
      "Eimi",
      "Ema",
      "Emi",
      "Emika",
      "Emiko",
      "Emiri",
      "Eri",
      "Erika",
      "Eriko",
      "Erina",
      "Etsuko",
      "Fubuki",
      "Fujie",
      "Fujiko",
      "Fūka",
      "Fukumi",
      "Fumi",
      "Fumie",
      "Fumika",
      "Fumiko",
      "Fumino",
      "Fusako",
      "Futaba",
      "Fuyuko",
      "Fuyumi",
      "Ginko",
      "Hana",
      "Hanae",
      "Hanako",
      "Harue",
      "Haruhi",
      "Haruko",
      "Haruna",
      "Haruno",
      "Haruyo",
      "Hasumi",
      "Hatsue",
      "Hatsumi",
      "Hatsune",
      "Hibari",
      "Hideko",
      "Himawari",
      "Himiko",
      "Hina",
      "Hinako",
      "Hiroe",
      "Hiroka",
      "Hiroko",
      "Hiroyo",
      "Hisa",
      "Hisae",
      "Hisako",
      "Hisayo",
      "Hitomi",
      "Hiyori",
      "Honami",
      "Honoka",
      "Ichigo",
      "Ichiko",
      "Ikue",
      "Ikuko",
      "Ikumi",
      "Ikuyo",
      "Inori",
      "Io",
      "Iroha",
      "Isuzu",
      "Ito",
      "Itsuko",
      "Itsumi",
      "Iyo",
      "Jitsuko",
      "Junko",
      "Juri",
      "Kaede",
      "Kaho",
      "Kahori",
      "Kahoru",
      "Kako",
      "Kana",
      "Kanae",
      "Kanako",
      "Kanami",
      "Kanna",
      "Kanoko",
      "Kanon",
      "Kaori",
      "Kaoruko",
      "Karen",
      "Karin",
      "Kasumi",
      "Katsuko",
      "Katsura",
      "Kawai",
      "Kaya",
      "Kayoko",
      "Kazue",
      "Kazuha",
      "Kazuko",
      "Kazusa",
      "Kazuyo",
      "Keiki",
      "Keiko",
      "Kiara",
      "Kie",
      "Kiho",
      "Kiko",
      "Kiku",
      "Kikue",
      "Kikuko",
      "Kimi",
      "Kimiko",
      "Kimiyo",
      "Kinu",
      "Kinuko",
      "Kira",
      "Kirari",
      "Kirie",
      "Kiriko",
      "Kirino",
      "Kiyoko",
      "Kiyomi",
      "Kiyone",
      "Koharu",
      "Komako",
      "Konami",
      "Konomi",
      "Koruri",
      "Kotoe",
      "Kotoko",
      "Kotomi",
      "Kotono",
      "Kotori",
      "Kou",
      "Kozue",
      "Kumi",
      "Kumiko",
      "Kuniko",
      "Kuriko",
      "Kyoko",
      "Miyamori",
      "Maaya",
      "Machi",
      "Machiko",
      "Madoka",
      "Mahiro",
      "Maho",
      "Mai",
      "Maika",
      "Maiko",
      "Maimi",
      "Maki",
      "Makiko",
      "Mami",
      "Mamiko",
      "Mana",
      "Manaka",
      "Manami",
      "Mao",
      "Mari",
      "Marie",
      "Marika",
      "Mariko",
      "Marina",
      "Mariya",
      "Marumi",
      "Masae",
      "Masako",
      "Masayo",
      "Mashiro",
      "Masuko",
      "Matsuko",
      "Matsuri",
      "Maya",
      "Mayako",
      "Mayo",
      "Mayu",
      "Mayuka",
      "Mayuko",
      "Mayumi",
      "Megu",
      "Megumi",
      "Mei",
      "Meiko",
      "Meisa",
      "Michi",
      "Michie",
      "Michiko",
      "Midori",
      "Mie",
      "Mieko",
      "Miharu",
      "Miho",
      "Mihoko",
      "Miiko",
      "Mika",
      "Mikako",
      "Miki",
      "Mikiko",
      "Miku",
      "Mikuru",
      "Mima",
      "Mori",
      "Mimori",
      "Mina",
      "Minae",
      "Minako",
      "Minami",
      "Mineko",
      "Mio",
      "Mioko",
      "Miori",
      "Mira",
      "Miri",
      "Misa",
      "Misaki",
      "Misako",
      "Misato",
      "Misono",
      "Misumi",
      "Misuzu",
      "Mitsuba",
      "Mitsuki",
      "Mitsuko",
      "Mitsuyo",
      "Miu",
      "Miwa",
      "Miwako",
      "Miya",
      "Miyabi",
      "Miyako",
      "Miyo",
      "Miyoko",
      "Miyoshi",
      "Miyū",
      "Miyuki",
      "Miyumi",
      "Mizue",
      "Mizuko",
      "Moa",
      "Moe",
      "Moeka",
      "Moeko",
      "Momiji",
      "Momo",
      "Momoe",
      "Momoha",
      "Momoka",
      "Momoko",
      "Momona",
      "Mone",
      "Motoko",
      "Murasaki",
      "Mutsuko",
      "Mutsumi",
      "Nagako",
      "Naho",
      "Nako",
      "Nami",
      "Namie",
      "Nana",
      "Nanae",
      "Nanako",
      "Nanami",
      "Nanase",
      "Nao",
      "Naoko",
      "Naru",
      "Naruko",
      "Narumi",
      "Natsue",
      "Natsuko",
      "Natsume",
      "Natsumi",
      "Nene",
      "Nina",
      "Noa",
      "Nobue",
      "Nobuko",
      "Nodoka",
      "Nonoka",
      "Noriko",
      "Noriyo",
      "Otoha",
      "Otome",
      "Ren",
      "Ran",
      "Ranko",
      "Reika",
      "Reiko",
      "Reina",
      "Remi",
      "Rena",
      "Reona",
      "Rie",
      "Rieko",
      "Riho",
      "Rika",
      "Rikako",
      "Riko",
      "Rina",
      "Rinka",
      "Rinko",
      "Rino",
      "Rio",
      "Risa",
      "Risako",
      "Ritsuko",
      "Ruka",
      "Rumi",
      "Rumiko",
      "Rumina",
      "Runa",
      "Ruri",
      "Ruriko",
      "Ryōka",
      "Ryōko",
      "Sachi",
      "Sachie",
      "Sachiko",
      "Sadako",
      "Sae",
      "Saeko",
      "Saiko",
      "Saki",
      "Sakie",
      "Sakiko",
      "Saku",
      "Sakura",
      "Sakurako",
      "Sana",
      "Sanae",
      "Sanami",
      "Saori",
      "Sari",
      "Sarina",
      "Satoko",
      "Satomi",
      "Sawa",
      "Sawako",
      "Saya",
      "Sayaka",
      "Sayako",
      "Sayo",
      "Sayoko",
      "Sayori",
      "Sayuki",
      "Sayumi",
      "Sayuri",
      "Sora",
      "Seiko",
      "Seina",
      "Seira",
      "Setsuko",
      "Shigeko",
      "Shiho",
      "Shihori",
      "Shiina",
      "Shimako",
      "Shina",
      "Shinako",
      "Shino",
      "Shiori",
      "Shizue",
      "Shizuka",
      "Shizuko",
      "Shizuku",
      "Shizuru",
      "Shōko",
      "Shuka",
      "Shuko",
      "Sonoko",
      "Sugako",
      "Sumi",
      "Sumie",
      "Sumika",
      "Sumiko",
      "Sumire",
      "Suzu",
      "Suzue",
      "Suzuka",
      "Suzuko",
      "Suzuna",
      "Tae",
      "Taeko",
      "Takako",
      "Takayo",
      "Takeko",
      "Tamako",
      "Tamami",
      "Tamao",
      "Tamayo",
      "Tamiko",
      "Tao",
      "Tarako",
      "Tatsuko",
      "Tazuko",
      "Teiko",
      "Tenka",
      "Teruko",
      "Tokiko",
      "Toko",
      "Tokuko",
      "Tomie",
      "Tomiko",
      "Tomoka",
      "Tomoko",
      "Tomoyo",
      "Toshiko",
      "Toyoko",
      "Tsubaki",
      "Tsugumi",
      "Tsukiko",
      "Tsukushi",
      "Tsuneko",
      "Tsuru",
      "Ui",
      "Uki",
      "Umeko",
      "Umi",
      "Uta",
      "Utami",
      "Waka",
      "Wakaba",
      "Wakako",
      "Wakana",
      "Yae",
      "Yaeko",
      "Yako",
      "Yasue",
      "Yasuko",
      "Yayoi",
      "Yoka",
      "Yoko",
      "Yoriko",
      "Yoshiko",
      "Yoshino",
      "Yua",
      "Yui",
      "Yuika",
      "Yuiko",
      "Yuina",
      "Yuka",
      "Yukako",
      "Yukari",
      "Yukie",
      "Yukika",
      "Yukiko",
      "Yukina",
      "Yukino",
      "Yūko",
      "Yume",
      "Yumeko",
      "Yumi",
      "Yumie",
      "Yumika",
      "Yumiko",
      "Yuna",
      "Yuno",
      "Yuri",
      "Yuria",
      "Yurie",
      "Yurika",
      "Yuriko",
      "Yurina",
      "Yuumi",
      "Yuuna",
      "Yuzuki"
    ],
    "Origin": "Jepang",
    "Gender": "Female"
  },
  {
    "Name": [
      "Abigail",
      "Ada",
      "Addison",
      "Adelaide",
      "Adele",
      "Adora",
      "Adriana",
      "Agnes",
      "Aileen",
      "Alaina",
      "Alanna",
      "Alberta",
      "Albina",
      "Aleana",
      "Alexa",
      "Alexandra",
      "Alexandria",
      "Alexis",
      "Alice",
      "Alicia",
      "Alisha",
      "Alison",
      "Allyson",
      "Alma",
      "Althea",
      "Alvina",
      "Alyson",
      "Amanda",
      "Amber",
      "Amberley",
      "Amelia",
      "Amy",
      "Ana",
      "Andrea",
      "Angel",
      "Angela",
      "Angelica",
      "Angelina",
      "Angella",
      "Angie",
      "Anna",
      "Annabelle",
      "Annabeth",
      "Anne",
      "Annette",
      "Annie",
      "Antonia",
      "Aoki",
      "April",
      "Arabella",
      "Arda",
      "Ariana",
      "Ariel",
      "Arya",
      "Ash",
      "Ashley",
      "Astrid",
      "Aubrey",
      "Audra",
      "Audrey",
      "Aurora",
      "Autumn",
      "Averil",
      "Avis",
      "Azalea",
      "Babette",
      "Barb",
      "Barbara",
      "Beatrice",
      "Beatrix",
      "Beau",
      "Becca",
      "Becki",
      "Becky",
      "Belinda",
      "Bella",
      "Berenice",
      "Bertha",
      "Betsy",
      "Bettina",
      "Betty",
      "Beverly",
      "Bianca",
      "Blair",
      "Blake",
      "Blanche",
      "Bobbi",
      "Bobby",
      "Bonnie",
      "Braden",
      "Brandy",
      "Brenda",
      "Brianna",
      "Bridget",
      "Brielle",
      "Brilliana",
      "Brooklyn",
      "Brynlee",
      "Bryony",
      "Caden",
      "Calla",
      "Candy",
      "Cara",
      "Cari",
      "Carina",
      "Carissa",
      "Carlena",
      "Carlene",
      "Carlie",
      "Carly",
      "Carmelita",
      "Carol",
      "CarolAnn",
      "CarolAnne",
      "Carole",
      "Carolina",
      "Caroline",
      "Carolyn",
      "CarrieAnn",
      "CarrieAnne",
      "Carroll",
      "Carry",
      "Carson",
      "Cary",
      "Casey",
      "Cassandra",
      "Cassidy",
      "Cathleen",
      "Cathy",
      "Cecilia",
      "Cecily",
      "Celestia",
      "Celia",
      "Celinda",
      "Chara",
      "Charis",
      "Charisse",
      "Charity",
      "Charla",
      "Charle",
      "Charlee",
      "Charlene",
      "Charley",
      "Charli",
      "Charlie",
      "Charlotte",
      "Charly",
      "Charlyne",
      "Charmaine",
      "Chas",
      "Chelsea",
      "Cherry",
      "Cheryl",
      "Chloe",
      "Christabel",
      "Christina",
      "Christine",
      "Christy",
      "Cindy",
      "Claire",
      "Clara",
      "Clare",
      "Claribel",
      "Clarice",
      "Clarissa",
      "Claudia",
      "Clementine",
      "Clover",
      "Cody",
      "Colette",
      "Colleen",
      "Cora",
      "Coral",
      "Coraline",
      "Cordelia",
      "Courtney",
      "Crystal",
      "Cynthia",
      "Daenerys",
      "Daisy",
      "Dana",
      "Dani",
      "Danielle",
      "Danna",
      "Daphne",
      "Darla",
      "Darlene",
      "Davina",
      "Dawn",
      "Deanna",
      "Deanne",
      "Debbie",
      "Deborah",
      "Dede",
      "Deja",
      "Delaney",
      "Delia",
      "Demetria",
      "Demi",
      "Destiny",
      "Devon",
      "Diamond",
      "Diana",
      "Diane",
      "Dimity",
      "Donna",
      "Dora",
      "Doreen",
      "Doris",
      "Dorothy",
      "Dottie",
      "Drew",
      "Dulcie",
      "Eadgifu",
      "Ealdgyth",
      "Ebony",
      "Edburga",
      "Eden",
      "Edith",
      "Edna",
      "Edris",
      "Edwina",
      "Effie",
      "Eileen",
      "Elaine",
      "Eleanor",
      "Elektra",
      "Elena",
      "Elisha",
      "Eliza",
      "Elizabeth",
      "Ella",
      "Elle",
      "Ellen",
      "Ellie",
      "Ellis",
      "Elora",
      "Emerald",
      "Emily",
      "Emma",
      "Enid",
      "Erika",
      "Erin",
      "Estelle",
      "Esther",
      "Esty",
      "Ethel",
      "Ethelreda",
      "Etty",
      "Eudora",
      "Eva",
      "Evan",
      "Eve",
      "Evelyn",
      "Fabienne",
      "Faith",
      "Faye",
      "Felicity",
      "Fern",
      "Finn",
      "Fiona",
      "Fleur",
      "Florence",
      "Frances",
      "Francie",
      "Francine",
      "Frederica",
      "Frida",
      "Gage",
      "Gale",
      "Gemma",
      "Georgene",
      "Georgia",
      "Georgiana",
      "Georgina",
      "Gia",
      "Gina",
      "Ginny",
      "Giselle",
      "Glenda",
      "Glenna",
      "Gloria",
      "Glynis",
      "Goldie",
      "Grace",
      "Gwen",
      "Gwenda",
      "Gwendolen",
      "Gwendoline",
      "Gwendolyn",
      "Gwyneth",
      "Haisley",
      "Haley",
      "Hannah",
      "Harmony",
      "Harriet",
      "Hayden",
      "Hayley",
      "Hazel",
      "Heather",
      "Heidi",
      "Helen",
      "Helena",
      "Helene",
      "Henrietta",
      "Hester",
      "Hilary",
      "Hilda",
      "Hodierna",
      "Holly",
      "Honor",
      "Hope",
      "Ida",
      "Imelda",
      "Imogen",
      "Ingrid",
      "Iona",
      "Irene",
      "Iris",
      "Irma",
      "Isa",
      "Isabel",
      "Isabella",
      "Isla",
      "Ivy",
      "Jacinta",
      "Jacqueline",
      "Jade",
      "Jan",
      "Jana",
      "Jane",
      "Janee",
      "Janelle",
      "Janet",
      "Janey",
      "Janie",
      "January",
      "Jasmine",
      "Jay",
      "Jayda",
      "Jayden",
      "Jayne",
      "Jaynie",
      "Jeanne",
      "Jeanie",
      "Jeannie",
      "Jemima",
      "Jemma",
      "Jenna",
      "Jennifer",
      "Jenny",
      "Jensen",
      "Jerri",
      "Jerry",
      "Jess",
      "Jessica",
      "Jessie",
      "Jill",
      "Joanna",
      "Joanne",
      "Jodi",
      "Jodie",
      "Jody",
      "Joelle",
      "Jolie",
      "Josephine",
      "Josie",
      "Joy",
      "Joyce",
      "Judith",
      "Julia",
      "Julianne",
      "Julie",
      "Juliet",
      "June",
      "Justine",
      "Kailey",
      "Kalla",
      "Kara",
      "Karen",
      "Karin",
      "Karlee",
      "Karlene",
      "Karli",
      "Karlie",
      "Karly",
      "Karolyn",
      "Karrie",
      "Karyn",
      "Karyne",
      "Kasey",
      "Kate",
      "Katey",
      "Kathleen",
      "Kathryn",
      "Kathy",
      "Katie",
      "Katina",
      "Katrina",
      "Katy",
      "Kay",
      "Kayla",
      "Kaylee",
      "Kelly",
      "Kelsey",
      "Kierra",
      "Kim",
      "Kimberly",
      "Kira",
      "Kirsteen",
      "Kirstin",
      "Kitty",
      "Krista",
      "Kristen",
      "Kristi",
      "Kristin",
      "Kristy",
      "Kylie",
      "Kyra",
      "Lacey",
      "Lana",
      "Lanna",
      "Lara",
      "Larissa",
      "Laura",
      "Laurel",
      "Lauren",
      "Laurence",
      "Lauretta",
      "Laurie",
      "Lauryn",
      "Lavender",
      "Leanne",
      "Lee",
      "Leila",
      "Leisha",
      "Lena",
      "Lenna",
      "Leona",
      "Leonora",
      "Leslie",
      "Lettice",
      "Lexi",
      "Lila",
      "Liliana",
      "Lilibet",
      "Lilibeth",
      "Lilla",
      "Lillian",
      "Lillie",
      "Lilly",
      "Lily",
      "Lina",
      "Linda",
      "Lindsay",
      "Lindy",
      "Lisa",
      "Liza",
      "Lizzie",
      "Loraine",
      "Lorena",
      "Loretta",
      "Lori",
      "Lorinda",
      "Lorna",
      "Lorraine",
      "Louella",
      "Louisa",
      "Louise",
      "Lucia",
      "Lucinda",
      "Lucy",
      "Lydia",
      "Lyndsay",
      "Lynnette",
      "Lysette",
      "Mabel",
      "Mable",
      "Macy",
      "Madelaine",
      "Madeleine",
      "Madelyn",
      "Madge",
      "Madison",
      "Madonna",
      "Mae",
      "Maggie",
      "Magnolia",
      "Mallory",
      "Mandy",
      "Mara",
      "Marcia",
      "Marcie",
      "Margaret",
      "Margie",
      "Margo",
      "Maria",
      "Mariah",
      "Marian",
      "Marianne",
      "Marie",
      "Marigold",
      "Marigold",
      "Marilyn",
      "Marina",
      "Marissa",
      "Marjorie",
      "Marlene",
      "Marsha",
      "Marta",
      "Martina",
      "Mary",
      "MaryBelle",
      "Mason",
      "Matilda",
      "Maude",
      "Maura",
      "Maureen",
      "Mavis",
      "Maxine",
      "Maxine",
      "May",
      "Maya",
      "Mayola",
      "McKenna",
      "Meara",
      "Medea",
      "Megan",
      "Mehitable",
      "Mel",
      "Melanie",
      "Melina",
      "Melinda",
      "Melissa",
      "Melody",
      "Mercedes",
      "Meredith",
      "Merilyn",
      "Merle",
      "Merrilyn",
      "Mia",
      "Michele",
      "Michelle",
      "Mila",
      "Mildred",
      "Miley",
      "Millicent",
      "Millie",
      "Mina",
      "Mindi",
      "Mindy",
      "Minnie",
      "Mira",
      "Miranda",
      "Miriam",
      "Misty",
      "Moira",
      "Molly",
      "Muriel",
      "Myra",
      "Nadia",
      "Nadine",
      "Naila",
      "Naomi",
      "Narcissa",
      "Nathalie",
      "Nia",
      "Nicole",
      "Nikki",
      "Nina",
      "Noel",
      "Noella",
      "Noelle",
      "Odette",
      "Olive",
      "Olivia",
      "Paige",
      "Palmer",
      "Pamela",
      "Paris",
      "Patience",
      "Patrice",
      "Patsy",
      "Patty",
      "Paula",
      "Paulina",
      "Pearl",
      "Peggy",
      "Penelope",
      "Penny",
      "Pepper",
      "Perry",
      "Persis",
      "Petra",
      "Petrina",
      "Petula",
      "Petunia",
      "Philippa",
      "Phoebe",
      "Pixie",
      "Posy",
      "Precious",
      "Primrose",
      "Priscilla",
      "Quendrida",
      "Rachel",
      "Rain",
      "Raleigh",
      "Ramona",
      "Randy",
      "Reba",
      "Rebecca",
      "Regina",
      "Renesmee",
      "Rhiannon",
      "Rhoda",
      "Rhonda",
      "Riley",
      "Risa",
      "Rita",
      "Roberta",
      "Robin",
      "Romilda",
      "Ronnie",
      "Rosaleen",
      "Rosalie",
      "Rosalind",
      "Rosalyn",
      "Rosamund",
      "Rose",
      "Rosemary",
      "Rosie",
      "Ruby",
      "Russi",
      "Ruth",
      "Sabrina",
      "Sadie",
      "Salma",
      "Sam",
      "Samantha",
      "Sandi",
      "Sandra",
      "Sandy",
      "Sapphire",
      "Sarah",
      "Sarina",
      "Sasha",
      "Scarlett",
      "Selena",
      "Selma",
      "Serena",
      "Shania",
      "Sharla",
      "Sharleen",
      "Sharlene",
      "Sharon",
      "Sheena",
      "Shelley",
      "Sherry",
      "Sheryl",
      "Shirley",
      "Sibyl",
      "Sid",
      "Sidney",
      "Sienna",
      "Sierra",
      "Simone",
      "Sky",
      "Skyler",
      "Sophia",
      "Sophie",
      "Sorrel",
      "Stacy",
      "Stella",
      "Stephanie",
      "Stevie",
      "Stratus",
      "Sue",
      "Summer",
      "Sunngifu",
      "Susan",
      "Susanna",
      "Susanne",
      "Sutton",
      "Suzanne",
      "Syd",
      "Sydney",
      "Sylvia",
      "Sylvie",
      "Tabitha",
      "Talitha",
      "Tamara",
      "Tara",
      "Taylor",
      "Teresa",
      "Terry",
      "Thelma",
      "Thomasina",
      "Tiffany",
      "Tigerlily",
      "Tori",
      "Torres",
      "Torrie",
      "Tracy",
      "Trish",
      "Trisha",
      "Trudy",
      "Tyler",
      "Tyra",
      "Ursula",
      "Val",
      "Valarie",
      "Valda",
      "Valerie",
      "Vanessa",
      "Velma",
      "Velma",
      "Velvet",
      "Venetia",
      "Venus",
      "Vera",
      "Veronica",
      "Vicky",
      "Victoria",
      "Vilma",
      "Viola",
      "Violet",
      "Violette",
      "Virginia",
      "Vivian",
      "Wanda",
      "Waverly",
      "Wednesday",
      "Wendy",
      "Whitney",
      "Wilma",
      "Wilson",
      "Winifred",
      "Winnie",
      "Winnifred",
      "Yancy",
      "Yasmin",
      "Yvette",
      "Yvonne"
    ],
    "Origin": "Inggris",
    "Gender": "Female"
  },
  {
    "Name": [
      "Adinda",
      "Agustina",
      "Amanda",
      "Ambar",
      "Ambarsari",
      "Ambarwati",
      "Amelia",
      "Amirah",
      "Ana",
      "Anandya",
      "Anastasia",
      "Andini",
      "Anggraeni",
      "Anggraini",
      "Anindya",
      "Anis",
      "Anita",
      "Anna",
      "Anne",
      "Annisa",
      "Aprilia",
      "Apriyana",
      "Arum",
      "Aryani",
      "Asmara",
      "Astrid",
      "Aulia",
      "Aurel",
      "Aurelia",
      "Bianca",
      "Cantika",
      "Citra",
      "Clara",
      "Clarissa",
      "Claudia",
      "Cynthia",
      "Dea",
      "Delia",
      "Deswita",
      "Desyana",
      "Dewi",
      "Dian",
      "Eka",
      "Ela",
      "Elena",
      "Elvira",
      "Fadilah",
      "Febri",
      "Fitri",
      "Fransisca",
      "Freya",
      "Gabriella",
      "Gendis",
      "Gina",
      "Gisella",
      "Gracia",
      "Ica",
      "Ima",
      "Imma",
      "Imtiyas",
      "Indrawati",
      "Inne",
      "Intan",
      "Ira",
      "Kartika",
      "Keira",
      "Kiki",
      "Klara",
      "Lana",
      "Lariska",
      "Lastri",
      "Laura",
      "Lauren",
      "Laurentia",
      "Lestari",
      "Lina",
      "Mawar",
      "Melati",
      "Melissa",
      "Mentari",
      "Monita",
      "Nabila",
      "Nadia",
      "Nadine",
      "Natasha",
      "Natasya",
      "Naura",
      "Nayla",
      "Ninda",
      "Ningrum",
      "Nisa",
      "Novi",
      "Novia",
      "Novita",
      "Nur",
      "Octavia",
      "Okvita",
      "Olive",
      "Olivia",
      "Pertiwi",
      "Pradita",
      "Priscilla",
      "Puspita",
      "Putri",
      "Putriana",
      "Ratna",
      "Ratri",
      "Raya",
      "Renata",
      "Retno",
      "Rina",
      "Rizka",
      "Sabrina",
      "Safira",
      "Safitri",
      "Sarah",
      "Sari",
      "Sekar",
      "Septia",
      "Silfia",
      "Silvia",
      "Sofia",
      "Syifa",
      "Tantri",
      "Tiara",
      "Tiwi",
      "Tyas",
      "Venna",
      "Vivi",
      "Widya",
      "Widyawati",
      "Wulan",
      "Wulandari",
      "Yeni"
    ],
    "Origin": "Indonesia",
    "Gender": "Female"
  },
  {
    "Name": [
      "Arty",
      "Chun",
      "Chunchen",
      "Chunxia",
      "Chunyu",
      "Chuyu",
      "Dazhi",
      "Deming",
      "Dezhu",
      "Dishan",
      "Fei-Fei",
      "Fen",
      "Fuju",
      "Gahui",
      "Gua",
      "Guiqing",
      "Guiying",
      "Guoyu",
      "Haiwei",
      "han",
      "Hongmin",
      "Hua",
      "Huang",
      "Ing-wen",
      "Jia",
      "Jiahui",
      "Jialin",
      "Jian",
      "Jiang",
      "Jianjun",
      "Jiannan",
      "Jing",
      "Jinghong",
      "Jingmei",
      "Jinyu",
      "Juri",
      "Lan",
      "Li",
      "Lijie",
      "Lin",
      "Ling",
      "Lingguang",
      "Liu",
      "Liyuu",
      "LongJie",
      "Lu",
      "Lumin",
      "Lusi",
      "Luyun",
      "Mei",
      "Meiling",
      "Meki",
      "Mi",
      "Ming",
      "Mingde",
      "Mingyu",
      "Mingzhi",
      "Mingzhu",
      "Nie",
      "Ping",
      "Pingping",
      "Qian",
      "Qiang",
      "Qianzhen",
      "Qing",
      "Qingling",
      "Qingqing",
      "Qiuming",
      "Qizhang",
      "Ronghua",
      "Rui",
      "Shania",
      "Shanshan",
      "Shi",
      "Shie",
      "Shijia",
      "Shijian",
      "Shilin",
      "Shujiao",
      "Shuo",
      "Sia",
      "Sian",
      "Sie",
      "Siwei",
      "Soo",
      "Thia",
      "Tingting",
      "Tuo",
      "Wei",
      "Wenxin",
      "Xia",
      "Xiao",
      "Xiaogang",
      "Xiaoling",
      "Xiaoming",
      "Xiaorou",
      "Xiaoyan",
      "Xiaoyu",
      "Xin",
      "Xingtian",
      "Xinrui",
      "Xu",
      "Xuan",
      "Xue",
      "Xuejian",
      "Yang",
      "Yanmin",
      "Yanyi",
      "Yaya",
      "Yinghua",
      "Yingwen",
      "You",
      "Youchang",
      "Youyi",
      "Yu",
      "Yuan",
      "Yuanyuan",
      "Yue",
      "Yumei",
      "Yunfei",
      "Yunzhu",
      "Zhao",
      "Ziming"
    ],
    "Origin": "China",
    "Gender": "Female"
  },
  {
    "Name": [
      "Elena Aoki",
      "Chihiro Yoshioka",
      "Nana Mifune",
      "Hikawa",
      "Sayaka Koyanagi",
      "Aiko",
      "Honoka",
      "Izumi",
      "Miku Aihara"
    ],
    "Origin": "Gleipnir",
    "Gender": "Female"
  },
  {
    "Name": [
      "Matsumoto Rangiku",
      "Rukia Kuchiki",
      "Orihime Inoue",
      "Soi Fon",
      "Retsu Unohana",
      "Yachiru Kusajishi",
      "Tier Harribel",
      "Bambietta Basterbine",
      "Hiyori Sarugaki",
      "Momo Hinamori",
      "Shiba Kuukaku",
      "Nemu Kurotsuchi",
      "Senjumaru Shutara",
      "Karin Kurosaki",
      "Mashiro Kuna",
      "Nanao Ise",
      "Isane Kotetsu",
      "Yuzu Kurosaki",
      "Masaki Kurosaki",
      "Ikumi Unagiya",
      "Chan Sung-Sun",
      "Meninas McAllon",
      "Loly Aivirrne",
      "Kirio Hikifune",
      "Franceska Mila Rose",
      "Kiyone Kotetsu",
      "Shino Madarame",
      "Kanae Katagiri",
      "Nonomi Nomino",
      "Batsu'unsai Katori",
      "hasuka Hashihara",
      "Kanan Ogura",
      "Shiho Torajima",
      "Yoruichi Shihouin",
      "Tu Oderschvank Nelliel",
      "Yadoumaru Lisa",
      "Saitou Furoufushi"
    ],
    "Origin": "Bleach",
    "Gender": "Female"
  },
  {
    "Name": [
      "Reze",
      "Higashiyama Kobeni",
      "Asa Mitaka",
      "Yoru",
      "Himeno",
      "Akane Sawatari",
      "Fami"
    ],
    "Origin": "Chainsaw Man",
    "Gender": "Female"
  },
  {
    "Name": [
      "Shinobu Kochou",
      "Hinaki Ubuyashiki",
      "Nichika Ubuyashiki",
      "Kuina Ubuyashiki",
      "Kanata Ubuyashiki",
      "Kanroji Mitsuri",
      "Kanae Kochou",
      "Kanao Tsuyuri",
      "Ozaki",
      "Aoi Kanzaki",
      "Sumi Nakahara",
      "Kiyo Terauchi",
      "Naho Takada",
      "Nezuko Kamado",
      "Tamayo",
      "Susamaru",
      "Shizu Shinazugawa",
      "Kie Kamado",
      "Hanako Kamado",
      "Suyako Kamado",
      "Sumire Kamado",
      "Makomo",
      "Tokie",
      "Satoko",
      "Rei",
      "Teruko",
      "Fuku",
      "Hinatsuru",
      "Makio",
      "Suma",
      "Koinatsu",
      "Omitsu",
      "Sumi Shinazugawa",
      "Tsutako Tomioka",
      "Sayo",
      "Senri Ubuyashiki",
      "Akito Ubuyashiki",
      "Nakime",
      "Daki",
      "Mukago",
      "Ruka Rengoku",
      "Koyuki",
      "Uta",
      "Toko",
      "Yae"
    ],
    "Origin": "Kimetsu",
    "Gender": "Female"
  },
  {
    "Name": [
      "Belo Betty",
      "Black Maria",
      "Boa Hancock",
      "Boa Marigold",
      "Boa Sandersonia",
      "Camie",
      "Carrot",
      "Catarina Devon",
      "Charlotte Chiffon",
      "Charlotte Flampe",
      "Charlotte Lola",
      "Charlotte Pudding",
      "Charlotte Smoothie",
      "Doll",
      "Domino",
      "Ginny",
      "Gion",
      "Hina",
      "Jewelry Bonney",
      "Kalifa",
      "Kaya",
      "Koala",
      "Kouzuki Hiyori",
      "Kouzuki Toki",
      "Kureha",
      "Lilith",
      "Makino",
      "Monet",
      "Nami",
      "Nefertari Vivi",
      "Nico Olvia",
      "Nico Robin",
      "Nojiko",
      "Perona",
      "Portgas D. Rouge",
      "Rebecca",
      "Shakky",
      "Shimotsuki Kuina",
      "Shirahoshi",
      "Stussy",
      "Tashigi",
      "Trafalgar Lami",
      "Ulti",
      "Uta",
      "Vinsmoke Reiju",
      "Yamato"
    ],
    "Origin": "One Piece",
    "Gender": "Female"
  },
  {
    "Name": [
      "Barbara Authen",
      "Becky Blackbell",
      "Camilla",
      "Chloe",
      "Fiona Frost",
      "Kim Campbell",
      "Martha Marriott",
      "Melinda Desmond",
      "Millie Myers",
      "Olka Gretcher",
      "Sharon",
      "Sylvia Sherwood",
      "Yor Briar",
      "Yor Forger"
    ],
    "Origin": "SPYxFAMILY",
    "Gender": "Female"
  },
  {
    "Name": [
      "Aejung",
      "Areum",
      "Bit Na",
      "Bitna",
      "Bo Ram",
      "Bo Reum",
      "Bo Young",
      "Bora",
      "Boram",
      "Boreum",
      "Boyoung",
      "Chae Won",
      "Chae Yeon",
      "Chae Young",
      "Chaewon",
      "Chaeyeon",
      "Chaeyoung",
      "Chun Hwa",
      "Chun Ja",
      "Chunhwa",
      "Chunja",
      "Da Hee",
      "Da Hye",
      "Da Rae",
      "Da Som",
      "Dahee",
      "Dahye",
      "Darae",
      "Dasom",
      "Do Hee",
      "Dohee",
      "Eun Ah",
      "Eun Bi",
      "Eun Byul",
      "Eun Chae",
      "Eun Ha",
      "Eun Hee",
      "Eun Hye",
      "Eun Ji",
      "Eun Jin",
      "Eun Ju",
      "Eun Jung",
      "Eun Kyung",
      "Eun Mi",
      "Eun Seo",
      "Eun Sook",
      "Eun Young",
      "Eunah",
      "Eunbi",
      "Eunbyul",
      "Eunchae",
      "Eunha",
      "Eunhee",
      "Eunhye",
      "Eunji",
      "Eunjin",
      "Eunju",
      "Eunjung",
      "Eunkyung",
      "Eunmi",
      "Eunseo",
      "Eunsook",
      "Eunyoung",
      "Ga Eul",
      "Ga Eun",
      "Ga In",
      "Ga Young",
      "Gaeul",
      "Gaeun",
      "Gain",
      "Gayoung",
      "Go Eun",
      "Goeun",
      "Gyuri",
      "Ha Eun",
      "Haeun",
      "Han Na",
      "Hana",
      "Hanna",
      "Hwa Young",
      "Hwayoung",
      "Hye Bin",
      "Hye In",
      "Hye Ja",
      "Hye Jeong",
      "Hye Jin",
      "Hye Kyung",
      "Hye Mi",
      "Hye Rim",
      "Hye Rin",
      "Hye Su",
      "Hye Won",
      "Hye Young",
      "Hyebin",
      "Hyein",
      "Hyeja",
      "Hyejeong",
      "Hyejin",
      "Hyekyung",
      "Hyemi",
      "Hyerim",
      "Hyerin",
      "Hyesu",
      "Hyewon",
      "Hyeyoung",
      "Hyo Joo",
      "Hyo Rin",
      "Hyojoo",
      "Hyorin",
      "Hyun A",
      "Hyun Kyung",
      "Hyun Mi",
      "Hyun Sook",
      "Hyuna",
      "Hyunkyung",
      "Hyunmi",
      "Hyunsook",
      "In Hye",
      "In Sook",
      "Inhye",
      "Insook",
      "Jang Mi",
      "Jangmi",
      "Jeong Ja",
      "Jeongja",
      "Ji Ae",
      "Ji Eun",
      "Ji Hye",
      "Ji Yeon",
      "Ji Young",
      "Jiae",
      "Jieun",
      "Jihye",
      "Jin Joo",
      "Jina",
      "Jinjoo",
      "Jiyeon",
      "Jiyoung",
      "Ju Hye",
      "Juhye",
      "Jung Ah",
      "Jung Sook",
      "Jung Soon",
      "Jungah",
      "Jungsook",
      "Jungsoon",
      "Kyung Ah",
      "Kyung Hwa",
      "Kyung Ja",
      "Kyung Ok",
      "Kyung Sook",
      "Kyungah",
      "Kyunghwa",
      "Kyungja",
      "Kyungok",
      "Kyungsook",
      "Mi Hee",
      "Mi Ja",
      "Mi Jung",
      "Mi Kyung",
      "Mi Rae",
      "Mi Ran",
      "Mi Sook",
      "Mi Yeon",
      "Mi Young",
      "Mihee",
      "Mija",
      "Mijung",
      "Mikyung",
      "Min Ji",
      "Min Ju",
      "Min Jung",
      "Min Kyung",
      "Min Seo",
      "Mina",
      "Minji",
      "Minju",
      "Minjung",
      "Minkyung",
      "Minseo",
      "Mirae",
      "Miran",
      "Misook",
      "Miyeon",
      "Miyoung",
      "Myung Hwa",
      "Myung Sook",
      "Myung Soon",
      "Myunghwa",
      "Myungsook",
      "Myungsoon",
      "Na Rae",
      "Na Young",
      "Narae",
      "Nari",
      "Nayoung",
      "Sa Rang",
      "Sang Mi",
      "Sangmi",
      "Sarang",
      "Seo Yeon",
      "Seol Hee",
      "Seolhee",
      "Seon Mi",
      "Seon Ok",
      "Seong Ja",
      "Seongja",
      "Seonmi",
      "Seonok",
      "Seoyeon",
      "Seung Ah",
      "Seungah",
      "Shin Hye",
      "Shinhye",
      "Si Eun",
      "Si Yeon",
      "Sieun",
      "Siyeon",
      "So Hee",
      "So Hye",
      "So Hyun",
      "So Won",
      "So Yeon",
      "So Yi",
      "So Young",
      "Sohee",
      "Sohye",
      "Sohyun",
      "Soo Ah",
      "Soo Jung",
      "Soo Min",
      "Sooah",
      "Soojung",
      "Sook Ja",
      "Sookja",
      "Soomin",
      "Soon Hee",
      "Soon Ja",
      "Soon Yi",
      "Soonhee",
      "Soonja",
      "Sora",
      "Sowon",
      "Soyeon",
      "Soyi",
      "Soyoung",
      "Su Hye",
      "Su Mi",
      "Suhye",
      "Sumi",
      "Sun Hee",
      "Sun Hwa",
      "Sun Ok",
      "Sung Mi",
      "Sung Sook",
      "Sungmi",
      "Sungsook",
      "Sunhee",
      "Sunhwa",
      "Sunok",
      "Ye Eun",
      "Ye Ji",
      "Ye Jin",
      "Ye Rin",
      "Ye Seo",
      "Ye Won",
      "Yebin",
      "Yeeun",
      "Yeji",
      "Yejin",
      "Yeo Jin",
      "Yeojin",
      "Yeon Hee",
      "Yeong Ok",
      "Yeongok",
      "Yeonhee",
      "Yerin",
      "Yeseo",
      "Yewon",
      "Yoo Jung",
      "Yoo Kyung",
      "Yoojung",
      "Yookyung",
      "Young Ae",
      "Young Ja",
      "Young Mi",
      "Young Sook",
      "Youngae",
      "Youngja",
      "Youngmi",
      "Youngsook",
      "Yu Ri",
      "Yumi",
      "Yun Suk",
      "Yunseo",
      "Yunsuk",
      "Yuri"
    ],
    "Origin": "Korean",
    "Gender": "Female"
  }
]
};

// Constants
const MAX_ATTEMPTS = 1000; // Maximum number of attempts to find a matching name
const TIMEOUT_MS = 2000; // Timeout in milliseconds

// DOM elements
const versionRadios = document.querySelectorAll('input[name="version"]');
const customSection = document.getElementById('custom-section');
const selectionSection = document.getElementById('selection-section');
const advancedFeaturesToggle = document.getElementById('toggle-advanced');
const advancedOptions = document.getElementById('advanced-options');
const nameWordsSelect = document.getElementById('name-words');
const suggestFirst = document.getElementById('suggest-first');
const suggestMiddle = document.getElementById('suggest-middle');
const suggestLast = document.getElementById('suggest-last');
const firstLetter = document.getElementById('first-letter');
const middleLetter = document.getElementById('middle-letter');
const lastLetter = document.getElementById('last-letter');

// Functions
function updateSelections(data) {
    const genderCheckboxes = document.getElementById('gender-checkboxes');
    const countryCheckboxes = document.getElementById('country-checkboxes');
    
    // Clear existing checkboxes
    genderCheckboxes.innerHTML = '';
    countryCheckboxes.innerHTML = '';

    // Get unique genders and countries
    const genders = [...new Set(data.map(item => item["Gender"]))];
    const countries = [...new Set(data.map(item => item.Origin))];

    // Create gender checkboxes
    genders.forEach(gender => {
        const label = document.createElement('label');
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.value = gender;
        checkbox.checked = true;
        label.appendChild(checkbox);
        label.appendChild(document.createTextNode(` ${gender}`));
        genderCheckboxes.appendChild(label);
    });

    // Create country checkboxes
    countries.forEach(country => {
        const label = document.createElement('label');
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.value = country;
        checkbox.checked = true;
        label.appendChild(checkbox);
        label.appendChild(document.createTextNode(` ${country}`));
        countryCheckboxes.appendChild(label);
    });
}

function toggleAdvancedFeatures() {
  const advancedFeatures = document.getElementById('advanced-features');
  const isCustomMode = document.querySelector('input[name="version"]:checked').value === 'custom';
  advancedFeatures.style.display = isCustomMode || versionRadios[0].checked ? 'block' : 'none';
}

function isAdvancedEnabled() {
  return document.getElementById('toggle-advanced').checked;
}

function copyToClipboard(button, text) {
    navigator.clipboard.writeText(text).then(() => {
        button.textContent = 'Copied';
        button.classList.add('copied');
        setTimeout(() => {
            button.textContent = 'Copy';
            button.classList.remove('copied');
        }, 2000);
    });
}

function copyAllNames() {
    const resultElements = document.querySelectorAll('.result span');
    const allNames = Array.from(resultElements).map(el => el.textContent).join('\n');
    
    const copyAllBtn = document.getElementById('copyAll');
    navigator.clipboard.writeText(allNames).then(() => {
        copyAllBtn.textContent = 'Copied All';
        copyAllBtn.classList.add('copied');
        setTimeout(() => {
            copyAllBtn.textContent = 'Copy All';
            copyAllBtn.classList.remove('copied');
        }, 2000);
    });
}

function updateMiddleNameOptions() {
    const nameWords = parseInt(nameWordsSelect.value);
    const middleNameOptions = document.querySelectorAll('.middle-name-option');
    middleNameOptions.forEach(option => {
        option.style.display = nameWords === 3 ? 'block' : 'none';
    });
}

// Event Listeners
// Initialize with default data
updateSelections([...defaultData.male, ...defaultData.female]);

versionRadios.forEach(radio => {
    radio.addEventListener('change', function() {
        if (this.value === 'custom') {
            customSection.style.display = 'block';
            selectionSection.style.display = 'none';
        } else {
            customSection.style.display = 'none';
            selectionSection.style.display = 'block';
            updateSelections([...defaultData.male, ...defaultData.female]);
        }
        toggleAdvancedFeatures();
    });
});

advancedFeaturesToggle.addEventListener('change', function() {
    advancedOptions.style.display = this.checked ? 'block' : 'none';
    if (this.checked) {
        updateMiddleNameOptions();
    } else {
        // Reset advanced options when disabled
        nameWordsSelect.value = '2';
        suggestFirst.value = '';
        suggestMiddle.value = '';
        suggestLast.value = '';
        firstLetter.value = '';
        middleLetter.value = '';
        lastLetter.value = '';
    }
});

nameWordsSelect.addEventListener('change', updateMiddleNameOptions);

document.getElementById('file').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = function(e) {
        try {
            const data = JSON.parse(e.target.result);
            customData = data;
            selectionSection.style.display = 'block';
            updateSelections(customData);
        } catch (err) {
            alert("Invalid JSON file");
        }
    };
    reader.readAsText(file);
});

document.getElementById('generate').addEventListener('click', function() {
    const selectedGenders = Array.from(document.querySelectorAll('#gender-checkboxes input:checked'))
        .map(checkbox => checkbox.value);
    const selectedCountries = Array.from(document.querySelectorAll('#country-checkboxes input:checked'))
        .map(checkbox => checkbox.value);

    if (selectedCountries.length === 0 || selectedGenders.length === 0) {
        alert("Please select at least one gender and one country");
        return;
    }

    let filteredNames = [];
    const isCustomMode = document.querySelector('input[name="version"]:checked').value === 'custom';
    
    if (isCustomMode) {
        filteredNames = customData
            .filter(item => 
                selectedCountries.includes(item.Origin) && 
                selectedGenders.includes(item["Gender"]))
            .flatMap(item => item.Name.flatMap(name => name.split(' ')));
    } else {
        const allNames = [...defaultData.male, ...defaultData.female];
        filteredNames = allNames
            .filter(item => 
                selectedCountries.includes(item.Origin) && 
                selectedGenders.includes(item["Gender"]))
            .flatMap(item => item.Name.flatMap(name => name.split(' ')));
    }

    if (filteredNames.length === 0) {
        alert("No names found for the selected options");
        return;
    }

    const results = document.getElementById('results');
    results.innerHTML = '';
    
    // Add Copy All button
    const copyAllBtn = document.createElement('button');
    copyAllBtn.id = 'copyAll';
    copyAllBtn.className = 'copy-btn copy-all-btn';
    copyAllBtn.textContent = 'Copy All';
    copyAllBtn.onclick = copyAllNames;
    results.appendChild(copyAllBtn);

    // Generate and display names
    for (let i = 0; i < 10; i++) {
        let mixedName = '';
        const nameWords = isAdvancedEnabled() ? parseInt(nameWordsSelect.value) : 2;

        for (let j = 0; j < nameWords; j++) {
            let name = '';
            if (isAdvancedEnabled()) {
                if (j === 0 && suggestFirst.value) {
                    name = suggestFirst.value;
                } else if (j === 1 && nameWords === 3 && suggestMiddle.value) {
                    name = suggestMiddle.value;
                } else if (j === nameWords - 1 && suggestLast.value) {
                    name = suggestLast.value;
                }
            }
            
            if (!name) {
                const startTime = Date.now();
                let attempts = 0;
                let letterToMatch = '';
                
                if (isAdvancedEnabled()) {
                    if (j === 0 && firstLetter.value) letterToMatch = firstLetter.value;
                    else if (j === 1 && nameWords === 3 && middleLetter.value) letterToMatch = middleLetter.value;
                    else if (j === nameWords - 1 && lastLetter.value) letterToMatch = lastLetter.value;
                }

                do {
                    name = filteredNames[Math.floor(Math.random() * filteredNames.length)];
                    attempts++;

                    if (Date.now() - startTime > TIMEOUT_MS || attempts > MAX_ATTEMPTS) {
                        name = `[No ${letterToMatch.toUpperCase()}-name found]`;
                        break;
                    }
                } while (
                    letterToMatch && !name.toLowerCase().startsWith(letterToMatch.toLowerCase())
                );
            }
            mixedName += (j > 0 ? ' ' : '') + name;
        }
        
        const resultDiv = document.createElement('div');
        resultDiv.className = 'result';
        resultDiv.innerHTML = `
            <span>${mixedName}</span>
            <button class="copy-btn" onclick="copyToClipboard(this, '${mixedName}')">Copy</button>
        `;
        results.appendChild(resultDiv);
    }
});

// Initialize
toggleAdvancedFeatures();
updateMiddleNameOptions();
